In [6]:
# Scholarship Eligibility Prediction using KNN

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import train_test_split

In [8]:
# 1. Load dataset
data = pd.read_csv("schlerships.csv")

# Show first rows
data.head()

,GPA,Orphanage,Disability,Community_Service,Family_Income_USD,Extracurricular_Activities,Disciplinary_Record,Scholarship_Status
0,3.28,No,Yes,Yes,438,Yes,Yes,Not Eligible
1,2.23,No,Yes,Yes,539,No,Yes,Not Eligible
2,2.68,No,No,Yes,1378,No,Yes,Not Eligible
3,3.53,No,No,Yes,154,No,No,Eligible
4,2.84,No,Yes,No,1680,Yes,Yes,Not Eligible

In [11]:
# 2. Dataset info
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 8 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   GPA                         600 non-null    float64
 1   Orphanage                   600 non-null    object
 2   Disability                  600 non-null    object
 3   Community_Service           600 non-null    object
 4   Family_Income_USD           600 non-null    int64
 5   Extracurricular_Activities  600 non-null    object
 6   Disciplinary_Record         600 non-null    object
 7   Scholarship_Status          600 non-null    object
dtypes: float64(1), int64(1), object(6)
memory usage: 37.6+ KB

In [12]:
# ==============================
# Convert Scholarship_Status to numeric
data["Scholarship_Status"] = data["Scholarship_Status"].map({
    "Eligible": 1,
    "Not Eligible": 0
})

In [13]:
# Separate X and y
X = data.drop("Scholarship_Status", axis=1)
y = data["Scholarship_Status"]

In [14]:
# Convert text columns into numbers
X = pd.get_dummies(X, drop_first=True)

In [15]:
X.head()

,GPA,Family_Income_USD,Orphanage_Yes,Disability_Yes,Community_Service_Yes,Extracurricular_Activities_Yes,Disciplinary_Record_Yes
0,3.28,438,False,True,True,True,True
1,2.23,539,False,True,True,False,True
2,2.68,1378,False,False,True,False,True
3,3.53,154,False,False,True,False,False
4,2.84,1680,False,True,False,True,True

In [16]:
# Split into training and testing
X_train, X_test, y_train, y_test = train_test_split(
    X,y,
    test_size=0.20,
    random_state=42
)

In [17]:
# 7. Scale the input features
# ==============================
# KNN uses distance, so scaling is very important
# because income and age may have different value ranges
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [18]:
# ==============================
# 8. Create the KNN model
# ==============================
# n_neighbors=5 means the model checks the 5 nearest customers
# before making a prediction
knn = KNeighborsClassifier(n_neighbors=5)

In [19]:
# 9. Train the model
# ==============================
knn.fit(X_train_scaled, y_train)

KNeighborsClassifier()

In [20]:
# ==============================
# 10. Make predictions
# ==============================
y_pred = knn.predict(X_test_scaled)

In [22]:
11. #Evaluate the model
# ==============================
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.975

In [24]:
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.95      0.98        64
           1       0.95      1.00      0.97        56

    accuracy                           0.97       120
   macro avg       0.97      0.98      0.97       120
weighted avg       0.98      0.97      0.98       120

In [25]:
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.95      0.98        64
           1       0.95      1.00      0.97        56

    accuracy                           0.97       120
   macro avg       0.97      0.98      0.97       120
weighted avg       0.98      0.97      0.98       120

In [26]:
# New student example
new_student = pd.DataFrame({
    "GPA": [3.5],
    "Orphanage": ["Yes"],
    "Disability": ["No"],
    "Community_Service": ["Yes"],
    "Family_Income_USD": [120],
    "Extracurricular_Activities": ["Yes"],
    "Disciplinary_Record": ["No"]
})

In [27]:
# Convert to numeric
new_student = pd.get_dummies(new_student, drop_first=True)

In [28]:
# Match with training columns
new_student = new_student.reindex(columns=X.columns, fill_value=0)

In [29]:
# Scale new student
new_student_scaled = scaler.transform(new_student)

In [30]:
# Predict
prediction = knn.predict(new_student_scaled)

if prediction[0] == 1:
    print("Prediction: Eligible for Scholarship")
else:
    print("Prediction: Not Eligible")

Prediction: Eligible for Scholarship