<a href="https://colab.research.google.com/github/MUHIYADIN2025/Schholarship_Project/blob/main/machine-learning/student_at_risk.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# DAY ONE - AI FOUNDATIONS AND SETUP

## loading and reviewing data

In [5]:
import pandas as pd

In [6]:
df= pd.read_csv("student-por.csv",sep=";")

In [7]:
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,4,0,11,11
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,2,9,11,11
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,6,12,13,12
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,0,14,14,14
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,0,11,13,13

In [8]:
df.tail()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
644,MS,F,19,R,GT3,T,2,3,services,other,...,5,4,2,1,2,5,4,10,11,10
645,MS,F,18,U,LE3,T,3,1,teacher,services,...,4,3,4,1,1,1,4,15,15,16
646,MS,F,18,U,GT3,T,1,1,other,other,...,1,1,1,1,1,5,6,11,12,9
647,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,6,10,10,10
648,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,4,10,11,11

In [9]:
df.shape

(649, 33)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 649 entries, 0 to 648
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      649 non-null    object
 1   sex         649 non-null    object
 2   age         649 non-null    int64
 3   address     649 non-null    object
 4   famsize     649 non-null    object
 5   Pstatus     649 non-null    object
 6   Medu        649 non-null    int64
 7   Fedu        649 non-null    int64
 8   Mjob        649 non-null    object
 9   Fjob        649 non-null    object
 10  reason      649 non-null    object
 11  guardian    649 non-null    object
 12  traveltime  649 non-null    int64
 13  studytime   649 non-null    int64
 14  failures    649 non-null    int64
 15  schoolsup   649 non-null    object
 16  famsup      649 non-null    object
 17  paid        649 non-null    object
 18  activities  649 non-null    object
 19  nursery     649 non-null    object
 20  higher      649 non-null    object
 21  internet    649 non-null    object
 22  romantic    649 non-null    object
 23  famrel      649 non-null    int64
 24  freetime    649 non-null    int64
 25  goout       649 non-null    int64
 26  Dalc        649 non-null    int64
 27  Walc        649 non-null    int64
 28  health      649 non-null    int64
 29  absences    649 non-null    int64
 30  G1          649 non-null    int64
 31  G2          649 non-null    int64
 32  G3          649 non-null    int64
dtypes: int64(16), object(17)
memory usage: 167.4+ KB

# Day 2 EDA

In [11]:
new_df = df.copy()

In [12]:
new_df.isnull().sum()

# isn()
new_df.isna().sum()

school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64

In [13]:
# drop()
new_df.drop(columns=["school"])
new_df


# drop index
new_df.drop(index=0)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,2,9,11,11
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,6,12,13,12
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,0,14,14,14
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,0,11,13,13
5,GP,M,16,U,LE3,T,4,3,services,other,...,5,4,2,1,2,5,6,12,12,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
644,MS,F,19,R,GT3,T,2,3,services,other,...,5,4,2,1,2,5,4,10,11,10
645,MS,F,18,U,LE3,T,3,1,teacher,services,...,4,3,4,1,1,1,4,15,15,16
646,MS,F,18,U,GT3,T,1,1,other,other,...,1,1,1,1,1,5,6,11,12,9
647,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,6,10,10,10
648,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,4,10,11,11

In [14]:
# dropna()
new_df.dropna()

# subset
new_df.dropna(subset=["school"])

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,4,0,11,11
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,2,9,11,11
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,6,12,13,12
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,0,14,14,14
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,0,11,13,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
644,MS,F,19,R,GT3,T,2,3,services,other,...,5,4,2,1,2,5,4,10,11,10
645,MS,F,18,U,LE3,T,3,1,teacher,services,...,4,3,4,1,1,1,4,15,15,16
646,MS,F,18,U,GT3,T,1,1,other,other,...,1,1,1,1,1,5,6,11,12,9
647,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,6,10,10,10
648,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,4,10,11,11

In [15]:
# filnna()
new_df["school"].mode()

0    GP
Name: school, dtype: object

In [16]:
new_df["school"]=new_df["school"].fillna(new_df["school"].mode()[0])

In [17]:
# numerical
new_df["age"].median()

17.0

In [18]:
new_df["age"].fillna(new_df["age"].median()).astype(int)

0      18
1      17
2      15
3      15
4      16
       ..
644    19
645    18
646    18
647    17
648    18
Name: age, Length: 649, dtype: int64

In [19]:
# dupliactes
# False, first,last
new_df[new_df.duplicated(keep="last")]

Empty DataFrame
Columns: [school, sex, age, address, famsize, Pstatus, Medu, Fedu, Mjob, Fjob, reason, guardian, traveltime, studytime, failures, schoolsup, famsup, paid, activities, nursery, higher, internet, romantic, famrel, freetime, goout, Dalc, Walc, health, absences, G1, G2, G3]
Index: []

[0 rows x 33 columns]

In [20]:
new_df=new_df.drop_duplicates()

In [21]:
new_df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,4,0,11,11
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,2,9,11,11
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,6,12,13,12
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,0,14,14,14
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,0,11,13,13

In [22]:
new_df["at_risk"]=(new_df["G3"]<10).astype(int)

In [23]:
new_df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3,at_risk
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,3,4,1,1,3,4,0,11,11,0
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,3,3,1,1,3,2,9,11,11,0
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,3,2,2,3,3,6,12,13,12,0
3,GP,F,15,U,GT3,T,4,2,health,services,...,2,2,1,1,5,0,14,14,14,0
4,GP,F,16,U,GT3,T,3,3,other,other,...,3,2,1,2,5,0,11,13,13,0

In [24]:
features = [
    "studytime", "failures", "schoolsup", "famsup", "activities",
    "higher", "internet", "famrel", "health", "absences"
]

X=new_df[features].copy()

In [25]:
X

,studytime,failures,schoolsup,famsup,activities,higher,internet,famrel,health,absences
0,2,0,yes,no,no,yes,no,4,3,4
1,2,0,no,yes,no,yes,yes,5,3,2
2,2,0,yes,no,no,yes,yes,4,3,6
3,3,0,no,yes,yes,yes,yes,3,5,0
4,2,0,no,yes,no,yes,no,4,5,0
...,...,...,...,...,...,...,...,...,...,...
644,3,1,no,no,yes,yes,yes,5,5,4
645,2,0,no,yes,no,yes,yes,4,1,4
646,2,0,no,no,yes,yes,no,1,5,6
647,1,0,no,no,no,yes,yes,2,2,6
648,1,0,no,no,no,yes,yes,4,5,4

In [26]:
Y=new_df["at_risk"]

In [27]:
Y

0      0
1      0
2      0
3      0
4      0
      ..
644    0
645    0
646    1
647    0
648    0
Name: at_risk, Length: 649, dtype: int64

In [28]:
class_balance= Y.value_counts()

In [29]:
class_balance

at_risk
0    549
1    100
Name: count, dtype: int64

In [30]:
model_data=X.copy()

In [31]:
model_data["at_risk"]=Y

In [32]:
model_data.head()

,studytime,failures,schoolsup,famsup,activities,higher,internet,famrel,health,absences,at_risk
0,2,0,yes,no,no,yes,no,4,3,4,0
1,2,0,no,yes,no,yes,yes,5,3,2,0
2,2,0,yes,no,no,yes,yes,4,3,6,0
3,3,0,no,yes,yes,yes,yes,3,5,0,0
4,2,0,no,yes,no,yes,no,4,5,0,0

In [33]:
model_data.to_csv(
    "student-cleaned-data.csv",
    index=False
)

In [53]:
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score
from sklearn.tree import DecisionTreeClassifier

In [41]:
X = model_data.drop(columns=['at_risk'])  # Beddel 'grade' haddii uu target-kaaga yahay column kale
y = 'at_risk'

In [44]:
X
Y

0      0
1      0
2      0
3      0
4      0
      ..
644    0
645    0
646    1
647    0
648    0
Name: at_risk, Length: 649, dtype: int64

In [46]:
X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size=0.2, random_state=42
)

In [48]:
# preprocessng

numeric_features = [
    "studytime",
    "failures",
    "famrel",
    "health",
    "absences"
]

categorical_features = [
    "schoolsup",
    "famsup",
    "activities",
    "higher",
    "internet"
]

preprocessor = ColumnTransformer([
    ("num", StandardScaler(), numeric_features),
    ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features)
])

In [55]:
dt_pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('model', DecisionTreeClassifier(random_state=42))
])

In [58]:
dt_pipeline.fit(X_train, Y_train)
Y_pred = dt_pipeline.predict(X_test)

In [59]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

accuracy = accuracy_score(Y_test, Y_pred)
precision = precision_score(Y_test, Y_pred)
recall = recall_score(Y_test, Y_pred)
f1 = f1_score(Y_test, Y_pred)

print("Accuracy :", accuracy)
print("Precision:", precision)
print("Recall   :", recall)
print("F1 Score :", f1)

Accuracy : 0.8307692307692308
Precision: 0.3333333333333333
Recall   : 0.4666666666666667
F1 Score : 0.3888888888888889

In [66]:
from google.colab import drive
import pickle

drive.mount('/content/drive')

with open('/content/drive/MyDrive/student_at_risk_decision_tree.pkl', 'wb') as file:
    pickle.dump(dt_pipeline, file)

Mounted at /content/drive

In [62]:
import os

if os.path.exists('/content/drive'):
    print("Google Drive is mounted.")
else:
    print("Google Drive is NOT mounted.")

Google Drive is NOT mounted.